### PR TITLE
Unchecked block code and validation improvements 

### PR DESCRIPTION
**Pull request by iamIcarus**
replaced 'unchecked' block with SafeMath sub
replaced 'if' with 'require' to validate inputs

### CODE REVIEW

**Review by MerlinEgalite — CHANGES_REQUESTED** [review]
Hi, thx for your contribution!

I'm not sure what is the motivation behind using `SafeMath` from OZ. Here it's not needed.

Also I used custom errors instead of revert to match last solidity standard, I'm not sure I'm willing to change it.

**Comment by iamIcarus** [comment]
@MerlinEgalite I will be using your code and I wanted to contribute :)

Basically I used `SafeMath` to get rid of the `unchecked` block. Ignore the `revert `, you are correct the solidity standard is custom errors. I'm using `revert ` as a habit from swift's `guard`

**Comment by MerlinEgalite** [comment]
Oh that's cool. How did you find it? (I just created it this weekend). As a disclaimer, the contract is not audited.

For `SafeMath` and the `sub`, I'm not sure it' necessary because the `unchecked` is here to save a bit of gas and this block:
```solidity
unchecked {
     amount = claimable - alreadyClaimed;
}
```
can't unerflow because we already know that `claimable > alreadyClaimed` thx to this this check:
```solidity
if (claimable <= alreadyClaimed) revert AlreadyClaimed();
```

**Comment by iamIcarus** [comment]
Ah i see , it does make sense for saving gas on that block

I was looking for a looking for a simple rewards distributor and i found it 😀

**Comment by MerlinEgalite** [comment]
> Ah i see , it does make sense for saving gas on that block
> 
> I was looking for a looking for a simple rewards distributor and i found it 😀

Awesome! Let me know on github or twitter when you use it!

**Comment by iamIcarus** [comment]
> > Ah i see , it does make sense for saving gas on that block
> > I was looking for a looking for a simple rewards distributor and i found it 😀
> 
> Awesome! Let me know on github or twitter when you use it!

Will do mate! Although my project is moving slower than I would like , I'm getting there  😀

**Pull request closed without merging**
