### PR TITLE
refactor: various optis

### PR DESCRIPTION
**Pull request by pakim249CAL**
This amount simplification is equivalent to the current logic as long as the amount claimable per account only strictly increases with each new root hash.

### CODE REVIEW

**Comment by MerlinEgalite** [comment]
> This amount simplification is equivalent to the current logic as long as the amount claimable per account only strictly increases with each new root hash.

I'm not sure why strictly? Can be constant (no new rewards for the user), right?

**Review by MerlinEgalite — CHANGES_REQUESTED** [review]
Nice! Can you format the code please?

**Comment by pakim249CAL** [comment]
> > This amount simplification is equivalent to the current logic as long as the amount claimable per account only strictly increases with each new root hash.
> 
> I'm not sure why strictly? Can be constant (no new rewards for the user), right?

Sorry yes you're right.

> Nice! Can you format the code please?

Do you mean with forge fmt? Because this results in many other files being formatted, so I wasn't sure if you wanted that. I can do it though.

**Comment by MerlinEgalite** [comment]
Maybe you can point to https://github.com/MerlinEgalite/universal-rewards-distributor/pull/4

**Pull request closed without merging**
